# Generated by Django 5.2 on 2025-05-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dqmmiaf0y/image/upload/v1714570701/default_profile_rqdzyf.jpg', upload_to='images/'),
        ),
    ]
